name: Orbiter
options:
  bundleIdPrefix: com.igm
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
    INFOPLIST_KEY_CFBundleDisplayName: Orbiter
targets:
  Orbiter:
    type: application
    platform: macOS
    sources:
      - path: Sources/Orbiter
        excludes:
          - "Orbiter.entitlements"
          - "PrivacyInfo.xcprivacy"
          - "AppIcon.icns"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Sources/Orbiter/Orbiter.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.igm.orbiter
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 igm. All rights reserved."
    resources:
      - path: Sources/Orbiter/PrivacyInfo.xcprivacy
      - path: Sources/Orbiter/Assets.xcassets
